#!/usr/bin/env python
# -*- coding: utf-8 -*-

import unittest
import logging
from unittest import TestLoader
from common.HTMLTestRunner import HTMLTestRunner
from test1.test1 import Test1
from test2.test2 import Test2

if __name__=='__main__':

    logging.basicConfig(level=logging.DEBUG,
                        format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s: %(message)s',
                        filename='Unittest.log',
                        filemode='w')

    test_classes = (Test1, Test2)

    suite = unittest.TestSuite()
    loader = TestLoader()
    for test_class in test_classes:
        tests = loader.loadTestsFromTestCase(test_class)
        suite.addTests(tests)

    with open('UnittestReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='Unit Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2)
        runner.run(suite)

